services:
  master:
    image: citusdata/citus
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

  worker1:
    image: citusdata/citus
    depends_on:
      - master
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres
    command:
      [
        "-c",
        "citus.worker_list_file=/etc/citus_worker_list.conf"
      ]
    volumes:
      - ./citus_worker_list.conf:/etc/citus_worker_list.conf

  worker2:
    image: citusdata/citus
    depends_on:
      - master
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres
    command:
      [
        "-c",
        "citus.worker_list_file=/etc/citus_worker_list.conf"
      ]
    volumes:
      - ./citus_worker_list.conf:/etc/citus_worker_list.conf

volumes:
  db_data: {}
